const app = require("express")();
const cors = require("cors");
app.use(cors());
const server = require("http").Server(app);
const io = require("socket.io")(server);
const PORT = 3000;
const sockets = {};
io.on("connection", (socket) => {
  console.log("new client connected");

  socket.on("connectInit", (sessionId) => {
    // The socket ID is stored along with the unique ID generated by the client
    sockets[sessionId] = socket.id;
    // The sockets object is stored in Express so it can be grabbed in a route
    app.set("sockets", sockets);
  });

  socket.on("uploadProgress",(dummyText)=>{
    console.log(dummyText);
    socket.emit("progressRce", "received");
  })
  // socket.emit("connection", null);
  // socket.on("connect", (data) => {
  //   console.log(data);
  // });
  // socket.on("disconnect", () => {
  //   console.log("user disconnected");
  // });
});
app.set("io", io);
server.listen(PORT, () => {
  console.log(`listening on *:${PORT}`);
});
